### ISSUE TITLE
Nested data key throws

### ISSUE THREAD

**Issue by panoply** [fauna/fauna-js#294] opened 2024-10-29 22:00 UTC
It seems rather absurd that nested keys using `data` property will throw. 

Take the following: 
```js
const update = {
   "name": "foo",
   "age": 30,
   "info": [
      {
          "sport": "boxing",
          "data": [
              {
                  "foo": "a"
              }
          ]
      }
   ]
}

client.query(fql`Example.byId('12345678090')?.update(${update})`)
```
Throws: 
```
TypeError: Passing function as a QueryArgument is not supported
```
This is because of the `data` property, which deeply nested within the structure, am I missing something here?

**Comment by ptpaterson** [comment] 2024-10-30 16:42
Hi @panoply Agreed there should be no issue with the query you shared. We cannot reproduce the error, though. Can you provide a minimal gist that reproduces it? What leads you to believe there is an issue with the nested `data` field? Here is me executing the same query
<img width="1357" alt="image" src="https://github.com/user-attachments/assets/4b0e9e56-74af-45c4-b7ae-b8809d86ba42">


The error indicates that you are trying to pass a function as an argument, and the `update` variable you show is clearly a plain old object.

**Comment by panoply** [comment] 2024-10-30 16:44
I am scratching my head here because the only difference with code sample and data is that its a getter reference.

**Comment by ptpaterson** [comment] 2024-10-30 16:55
Can you provide an example of what you mean? You cannot provide any object with functions as properties. If you are using a class instance as an argument, consider adding a "toObject" method that converts the class into a plain old object.

**Comment by ptpaterson** [comment] 2024-10-31 13:13
I'm going to close this issue, but please feel free to follow up if you continue to have problems or find anything else.

**Closed** 2024-10-31 13:14 UTC
